#!/usr/bin/env python3
"""rehorse-reports/PROGRESS.md, regenerated from state (never free-formed).
CLI: progress.py render | plan "<step>" ... (phase implement, clean worktree; records tests_sha) | add "<step>" ...
The SubagentStop hook that closes a step is step_done.py; verify.py records the verifier's verdict."""
import os
import sys

import state
import worktree

MAX_STEPS = 6


def wt_path(root, task):
    return os.path.realpath(os.path.join(root, task["worktree"]))


NEXT = {"setup": "no test command was detected: delegate the minimal test harness (and any refactor needed to make the code testable) "
                 "to a rehorse-step subagent, in the worktree, committed; then `testcmd.py set \"<cmd>\"` and `state.py advance spec`.",
        "spec": "write REHORSE_SPEC.md in the worktree, run the test command there once (baseline), then `state.py advance tests`.",
        "tests": "delegate the failing tests to a rehorse-step subagent (test paths only), run the test command in the worktree "
                 "(red_check: at least one failure), then `state.py advance implement` and `progress.py plan \"...\"`.",
        "report": "done; the user decides: /rehorse:merge %(id)s or /rehorse:discard %(id)s."}
VERIFY_NEXT = ("run `verify.py brief` and spawn a rehorse-verifier subagent (subagent_type rehorse:rehorse-verifier) with its "
               "output as the whole prompt.", "verdict %(verdict)s (round %(round)d): `report.py --summary \"...\"`.")


def counts(c):
    return "%d passed / %d failed" % (c["passed"], c["failed"]) if c else "not recorded"


def next_action(task):
    plan, i, v = task["plan"], task["step"], task.get("verifier")
    if task["phase"] == state.ATTENTION:
        return "needs attention: %s. When resolved, `state.py advance %s` resumes it; or /rehorse:discard %s." % (
            task["attention"]["reason"], task["attention"]["prior_phase"], task["id"])
    if task["phase"] == "verify":
        return VERIFY_NEXT[1] % v if v else VERIFY_NEXT[0]
    if task["phase"] != "implement":
        return NEXT.get(task["phase"], task["phase"]) % task
    return ("split the spec into 1-%d steps: `progress.py plan \"step\" ...`." % MAX_STEPS if not plan else
            "run step %d (%s) as a rehorse-step subagent." % (i + 1, plan[i]["title"]) if i < len(plan) else
            "all steps done: `state.py advance verify`.")


def section(root, task):
    tid, phase, plan = task["id"], task["phase"], task["plan"]
    if phase in state.TERMINAL:
        return "## %s: %s\n" % (tid, phase)
    lines = ["## %s (phase: %s%s)" % (tid, phase, ", step %d/%d" % (min(task["step"] + 1, len(plan)), len(plan)) if plan else "")]
    if phase == state.ATTENTION:
        lines.append("**NEEDS ATTENTION** (was in %s): %s" % (task["attention"]["prior_phase"], task["attention"]["reason"]))
    lines.append("- Spec: %s/REHORSE_SPEC.md %s" % (task["worktree"], worktree.spec_goal(wt_path(root, task))))
    lines.append("- Tests: `%s`; baseline %s; red %s; last %s" % (task["test_cmd"], counts(task["baseline"]), counts(task["red_check"]), counts(task["last_test_run"])))
    lines += ["- Plan:"] if plan else []
    for n, p in enumerate(plan, 1):
        done = ("" if not p["done"] else " — already satisfied by step %d (no edits; commit %s)" % (p["satisfied_by"], p["commit"])
                if p.get("satisfied_by") else " — %s (commit %s)" % (" ".join((p["summary"] or "").splitlines()), p["commit"]))
        lines.append("  - [%s] %d. %s%s" % ("x" if p["done"] else " ", n, p["title"], done))
    for v in (task.get("verify_history") or []) + [task["verifier"]] * bool(task.get("verifier")):
        lines.append("- Verifier: round %d %s (%d finding(s); its run %s)" % (v["round"], v["verdict"].upper(), len(v["findings"]), counts(v.get("tests"))))
    lines.append("- Next: " + next_action(task))
    return "\n".join(lines) + "\n"


def render(root, s):
    """Rewrite PROGRESS.md from state; active task first. Returns the text."""
    order = sorted(s["tasks"].values(), key=lambda t: (t["id"] != s["active_task"], t["created"]))
    text = "# Rehorse progress\n\nRegenerated by progress.py from .rehorse/state.json; edits here are overwritten.\n\n"
    text += "\n".join(section(root, t) for t in order) or "No tasks yet.\n"
    path = os.path.join(root, "rehorse-reports", "PROGRESS.md")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(text)
    return text


def set_plan(root, s, task, titles):
    if task["phase"] != "implement":
        raise ValueError("the plan is set in phase implement (task is in %s)" % task["phase"])
    if not 1 <= len(titles) <= MAX_STEPS:
        raise ValueError("a plan has 1-%d steps, got %d" % (MAX_STEPS, len(titles)))
    dirty = worktree.dirty(root, task["id"])
    if dirty:  # tests_sha must mark the end of the tests phase, so the red tests are committed before the plan exists
        raise ValueError("the worktree has uncommitted changes (%s); run `cd %s && git add -A && git commit -m \"tests: red for %s\"` first"
                         % (", ".join(dirty[:5]), wt_path(root, task), task["id"]))
    task["tests_sha"] = worktree.git(wt_path(root, task), "rev-parse", "HEAD").strip()
    task["plan"] = [{"title": t, "done": False, "summary": None, "commit": None} for t in titles]
    task["step"] = 0


def main(argv):
    root, s, task = state.active(os.getcwd())
    if not root or (not task and argv[:1] != ["render"]):
        sys.exit("progress.py: not inside a git repository" if not root else "progress.py: no active task")
    if argv[:1] == ["render"]:
        sys.stdout.write(render(root, s))
        return 0
    try:
        if argv[:1] == ["plan"]:
            set_plan(root, s, task, argv[1:])
        elif argv[:1] == ["add"] and argv[1:]:
            task["plan"] += [{"title": t, "done": False, "summary": None, "commit": None} for t in argv[1:]]
        else:
            sys.exit(__doc__)
    except ValueError as e:
        sys.exit("progress.py: %s" % e)
    state.save(root, s)
    render(root, s)
    print("Next: " + next_action(task))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
