#!/usr/bin/env python3
"""rehorse-reports/PROGRESS.md, regenerated from state (never free-formed), plus the SubagentStop hook that closes a step.
CLI: progress.py render | plan "<step>" ... (phase implement, clean worktree; records tests_sha) | add "<step>" ...
Hook: --step-done (SubagentStop). For a rehorse-step agent in tests/implement: block the stop while edits are newer than the
last test run or the worktree is uncommitted (reason names the command; 8th block -> needs-attention); else mark the step done.
"""
import json
import os
import sys

import guard_stop
import state
import worktree

STEP_AGENT = "rehorse-step"
MAX_STEPS = 6


def wt_path(root, task):
    return os.path.realpath(os.path.join(root, task["worktree"]))


NEXT = {"spec": "write REHORSE_SPEC.md in the worktree, run the test command there once (baseline), then `state.py advance tests`.",
        "tests": "delegate the failing tests to a rehorse-step subagent (test paths only), run the test command in the worktree "
                 "(red_check: at least one failure), then `state.py advance implement` and `progress.py plan \"...\"`.",
        "verify": "run the verifier, then `report.py`.",
        "report": "done; the user decides: /rehorse:merge %(id)s or /rehorse:discard %(id)s."}


def counts(c):
    return "%d passed / %d failed" % (c["passed"], c["failed"]) if c else "not recorded"


def next_action(task):
    plan, i = task["plan"], task["step"]
    if task["phase"] == state.ATTENTION:
        return "needs attention: %s. When resolved, `state.py advance %s` resumes it; or /rehorse:discard %s." % (
            task["attention"]["reason"], task["attention"]["prior_phase"], task["id"])
    if task["phase"] != "implement":
        return NEXT.get(task["phase"], task["phase"]) % task
    if not plan:
        return "split the spec into 1-%d steps: `progress.py plan \"step\" ...`." % MAX_STEPS
    return ("run step %d (%s) as a rehorse-step subagent." % (i + 1, plan[i]["title"]) if i < len(plan)
            else "all steps done: `state.py advance verify`.")


def goal(root, task):
    """First prose line of REHORSE_SPEC.md, or empty."""
    try:
        return next(l.strip() for l in open(os.path.join(wt_path(root, task), "REHORSE_SPEC.md")) if l.strip() and l[0] != "#")
    except (OSError, StopIteration):
        return ""


def section(root, task):
    tid, phase, plan = task["id"], task["phase"], task["plan"]
    if phase in state.TERMINAL:
        return "## %s: %s\n" % (tid, phase)
    lines = ["## %s (phase: %s%s)" % (tid, phase, ", step %d/%d" % (min(task["step"] + 1, len(plan)), len(plan)) if plan else "")]
    if phase == state.ATTENTION:
        lines.append("**NEEDS ATTENTION** (was in %s): %s" % (task["attention"]["prior_phase"], task["attention"]["reason"]))
    lines.append("- Spec: %s/REHORSE_SPEC.md %s" % (task["worktree"], goal(root, task)))
    lines.append("- Tests: `%s`; baseline %s; red %s; last %s" % (task["test_cmd"], counts(task["baseline"]),
                                                                  counts(task["red_check"]), counts(task["last_test_run"])))
    if plan:
        lines.append("- Plan:")
        for n, p in enumerate(plan, 1):
            done = " — %s (commit %s)" % (" ".join((p["summary"] or "").splitlines()), p["commit"]) if p["done"] else ""
            lines.append("  - [%s] %d. %s%s" % ("x" if p["done"] else " ", n, p["title"], done))
    lines.append("- Next: " + next_action(task))
    return "\n".join(lines) + "\n"


def render(root, s):
    """Rewrite PROGRESS.md from state; active task first. Returns the text."""
    order = sorted(s["tasks"].values(), key=lambda t: (t["id"] != s["active_task"], t["created"]))
    text = "# Rehorse progress\n\nRegenerated by progress.py from .rehorse/state.json; edits here are overwritten.\n\n"
    text += "\n".join(section(root, t) for t in order) or "No tasks yet.\n"
    path = os.path.join(root, "rehorse-reports", "PROGRESS.md")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(text)
    return text


def set_plan(root, s, task, titles):
    if task["phase"] != "implement":
        raise ValueError("the plan is set in phase implement (task is in %s)" % task["phase"])
    if not 1 <= len(titles) <= MAX_STEPS:
        raise ValueError("a plan has 1-%d steps, got %d" % (MAX_STEPS, len(titles)))
    dirty = worktree.dirty(root, task["id"])
    if dirty:  # tests_sha must mark the end of the tests phase, so the red tests are committed before the plan exists
        raise ValueError("the worktree has uncommitted changes (%s); run `cd %s && git add -A && git commit -m \"tests: red for %s\"` first"
                         % (", ".join(dirty[:5]), wt_path(root, task), task["id"]))
    task["tests_sha"] = worktree.git(wt_path(root, task), "rev-parse", "HEAD").strip()
    task["plan"] = [{"title": t, "done": False, "summary": None, "commit": None} for t in titles]
    task["step"] = 0


def step_done(hook):
    root, s, task = state.active(hook.get("cwd"))
    if not task or task["phase"] not in ("tests", "implement") or (hook.get("agent_type") or "").split(":")[-1] != STEP_AGENT:
        return 0
    wt, plan, i = wt_path(root, task), task["plan"], task["step"]
    title = plan[i]["title"] if task["phase"] == "implement" and i < len(plan) else None
    pending = task["edit_seq"] - (task.get("last_test_run") or {}).get("after_edit_seq", 0)
    if pending > 0:
        return guard_stop.block(root, s, task, "%d edit(s) since the last recorded test run. Run `cd %s && %s`, then stop again." % (pending, wt, task["test_cmd"]), "step-done")
    dirty = worktree.dirty(root, task["id"])
    if dirty:
        msg = "step %d: %s" % (i + 1, title) if title else "tests: red for %s" % task["id"]
        return guard_stop.block(root, s, task, "uncommitted changes in the worktree (%s). Run `cd %s && git add -A && git commit -m \"%s\"`, then stop again."
                     % (", ".join(dirty[:5]), wt, msg), "step-done")
    task["stop_blocks"] = 0
    if title:
        summary = [l.strip() for l in (hook.get("last_assistant_message") or "").splitlines() if l.strip()][:2]
        plan[i].update(done=True, summary="\n".join(summary), commit=worktree.git(wt, "rev-parse", "HEAD").strip()[:7])
        task["step"] = i + 1
    state.save(root, s)
    render(root, s)
    return 0


def main(argv):
    if argv[:1] == ["--step-done"]:
        return step_done(json.load(sys.stdin))
    root, s, task = state.active(os.getcwd())
    if not root or (not task and argv[:1] != ["render"]):
        sys.exit("progress.py: not inside a git repository" if not root else "progress.py: no active task")
    if argv[:1] == ["render"]:
        sys.stdout.write(render(root, s))
        return 0
    try:
        if argv[:1] == ["plan"]:
            set_plan(root, s, task, argv[1:])
        elif argv[:1] == ["add"] and argv[1:]:
            task["plan"] += [{"title": t, "done": False, "summary": None, "commit": None} for t in argv[1:]]
        else:
            sys.exit(__doc__)
    except ValueError as e:
        sys.exit("progress.py: %s" % e)
    state.save(root, s)
    render(root, s)
    print("Next: " + next_action(task))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
